# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fred Owens Project Showcase
email: owensf.fred@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Projectdiary
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  owensf

# Build settings
#theme: minima
#theme: jekyll-theme-midnight

# Specific to just-the-docs theme
remote_theme: pmarsceill/just-the-docs

# This is specific to just-the-docs
search_enabled: false
heading_anchors: false

# These two options add line numbers to the code snippets
compress_html:
  ignore:
    envs: all

#kramdown:
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true

# set the color scheme
color_scheme: light

# Aux links for the upper right navigation
aux_links:
  "My GitHub":
    - "//github.com/owensf"
  "My Resume":
    - "https://github.com/owensf/FredOwensResume/blob/master/Fred%20Owens%20Resume%207-12-23.pdf"
  "My Linkedin":
    - "https://www.linkedin.com/feed/"
    
    

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
